name: Deploy VuePress site to Pages

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued when a deployment is in progress
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # 최신 버전으로 사용
        with:
          fetch-depth: 0 # 모든 커밋 기록을 가져옵니다. gh-pages 브랜치 관련 작업에 필요.

      - name: Setup Node.js
        uses: actions/setup-node@v4 # 최신 버전으로 사용
        with:
          node-version: 20 # Node.js 버전을 프로젝트에 맞게 설정

      - name: Install dependencies
        run: npm ci # package-lock.json 을 사용하여 의존성을 설치합니다.

      - name: Build VuePress
        run: npm run docs:build # VuePress 빌드 명령어를 실행합니다.

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # 빌드 결과물을 업로드합니다.
        with:
          path: "./docs/.vuepress/dist" # VuePress 빌드 결과물의 경로를 지정합니다.

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # GitHub Pages로 배포하는 액션입니다.
